[versions]
androidx-lifecycle = "2.9.1"
composeHotReload = "1.0.0-beta04"
composeMultiplatform = "1.8.2"
junit = "4.13.2"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"
kotlin-logging = "7.0.13"
file-kit = "0.10.0"
spotify-webapi-java = "9.3.0"
lucide-icons = "1.0.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlin-logging-jvm = {module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging"}
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "file-kit"}
filekit-dialogs ={ module = "io.github.vinceglb:filekit-dialogs", version.ref = "file-kit"}
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "file-kit"}
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "file-kit"}
spotify-webapi-java = { module = "se.michaelthelin.spotify:spotify-web-api-java", version.ref = "spotify-webapi-java"}
lucide-icons = { module = "com.composables:icons-lucide", version.ref = "lucide-icons"}

[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
